create type "public"."role" as enum ('driver', 'user', 'admin');

create table "public"."Account" (
    "account_id" uuid not null default gen_random_uuid(),
    "username" text not null,
    "email" text not null,
    "role" role not null
);


alter table "public"."Account" enable row level security;

create table "public"."Driver" (
    "id" bigint generated by default as identity not null,
    "account_id" uuid,
    "rating" bigint,
    "availability_status" role,
    "license_number" bigint,
    "current_location" text
);


alter table "public"."Driver" enable row level security;

create table "public"."DriverBankInfo" (
    "id" bigint generated by default as identity not null,
    "driver_id" bigint,
    "transit_number" bigint,
    "account_number" bigint,
    "institution_number" bigint
);


alter table "public"."DriverBankInfo" enable row level security;

create table "public"."PasswordCredential" (
    "id" bigint generated by default as identity not null,
    "account_id" uuid not null,
    "password_hash" text not null
);


alter table "public"."PasswordCredential" enable row level security;

create table "public"."Payment" (
    "id" bigint generated by default as identity not null,
    "trip_id" bigint not null,
    "trip_amount" bigint not null,
    "tip" bigint,
    "payment_method" text not null,
    "status" boolean not null
);


alter table "public"."Payment" enable row level security;

create table "public"."Rating" (
    "id" bigint generated by default as identity not null,
    "trip_id" bigint,
    "driver_rating" bigint,
    "rider_rating" bigint
);


alter table "public"."Rating" enable row level security;

create table "public"."Rider" (
    "id" bigint generated by default as identity not null,
    "account_id" uuid,
    "rating" bigint
);


alter table "public"."Rider" enable row level security;

create table "public"."RiderBankInfo" (
    "id" bigint generated by default as identity not null,
    "rider_id" bigint,
    "card_number" text not null,
    "CVC" bigint not null,
    "expiration_date" date not null,
    "billing_address" text not null,
    "first_name" text not null,
    "last_name" text not null
);


alter table "public"."RiderBankInfo" enable row level security;

create table "public"."Token" (
    "id" bigint generated by default as identity not null,
    "account_id" uuid,
    "issued" timestamp without time zone,
    "expired" timestamp without time zone,
    "column" timestamp with time zone,
    "refresh_id" uuid default gen_random_uuid()
);


alter table "public"."Token" enable row level security;

create table "public"."Trip" (
    "id" bigint generated by default as identity not null,
    "driver_id" bigint,
    "rider_id" bigint,
    "status" role,
    "start_location" text,
    "end_location" text,
    "time_started" timestamp without time zone,
    "time_completed" timestamp without time zone
);


alter table "public"."Trip" enable row level security;

create table "public"."Vehicles" (
    "id" bigint generated by default as identity not null,
    "driver_id" bigint not null,
    "license_plate" text not null,
    "model" text,
    "make" text,
    "year" numeric,
    "colour" text,
    "insurance_number" bigint not null
);


alter table "public"."Vehicles" enable row level security;

CREATE UNIQUE INDEX "Account_email_key" ON public."Account" USING btree (email);

CREATE UNIQUE INDEX "Account_pkey" ON public."Account" USING btree (account_id);

CREATE UNIQUE INDEX "DriverBankInfo_pkey" ON public."DriverBankInfo" USING btree (id);

CREATE UNIQUE INDEX "Driver_pkey" ON public."Driver" USING btree (id);

CREATE UNIQUE INDEX "PasswordCredential_account_id_key" ON public."PasswordCredential" USING btree (account_id);

CREATE UNIQUE INDEX "PasswordCredential_pkey" ON public."PasswordCredential" USING btree (id);

CREATE UNIQUE INDEX "Payment_pkey" ON public."Payment" USING btree (id);

CREATE UNIQUE INDEX "Rating_pkey" ON public."Rating" USING btree (id);

CREATE UNIQUE INDEX "RiderBankInfo_pkey" ON public."RiderBankInfo" USING btree (id);

CREATE UNIQUE INDEX "Rider_pkey" ON public."Rider" USING btree (id);

CREATE UNIQUE INDEX "Token_pkey" ON public."Token" USING btree (id);

CREATE UNIQUE INDEX "Trip_pkey" ON public."Trip" USING btree (id);

CREATE UNIQUE INDEX "Vehicles_pkey" ON public."Vehicles" USING btree (id);

alter table "public"."Account" add constraint "Account_pkey" PRIMARY KEY using index "Account_pkey";

alter table "public"."Driver" add constraint "Driver_pkey" PRIMARY KEY using index "Driver_pkey";

alter table "public"."DriverBankInfo" add constraint "DriverBankInfo_pkey" PRIMARY KEY using index "DriverBankInfo_pkey";

alter table "public"."PasswordCredential" add constraint "PasswordCredential_pkey" PRIMARY KEY using index "PasswordCredential_pkey";

alter table "public"."Payment" add constraint "Payment_pkey" PRIMARY KEY using index "Payment_pkey";

alter table "public"."Rating" add constraint "Rating_pkey" PRIMARY KEY using index "Rating_pkey";

alter table "public"."Rider" add constraint "Rider_pkey" PRIMARY KEY using index "Rider_pkey";

alter table "public"."RiderBankInfo" add constraint "RiderBankInfo_pkey" PRIMARY KEY using index "RiderBankInfo_pkey";

alter table "public"."Token" add constraint "Token_pkey" PRIMARY KEY using index "Token_pkey";

alter table "public"."Trip" add constraint "Trip_pkey" PRIMARY KEY using index "Trip_pkey";

alter table "public"."Vehicles" add constraint "Vehicles_pkey" PRIMARY KEY using index "Vehicles_pkey";

alter table "public"."Account" add constraint "Account_email_key" UNIQUE using index "Account_email_key";

alter table "public"."Driver" add constraint "Driver_account_id_fkey" FOREIGN KEY (account_id) REFERENCES "Account"(account_id) not valid;

alter table "public"."Driver" validate constraint "Driver_account_id_fkey";

alter table "public"."DriverBankInfo" add constraint "DriverBankInfo_driver_id_fkey" FOREIGN KEY (driver_id) REFERENCES "Driver"(id) not valid;

alter table "public"."DriverBankInfo" validate constraint "DriverBankInfo_driver_id_fkey";

alter table "public"."PasswordCredential" add constraint "PasswordCredential_account_id_fkey" FOREIGN KEY (account_id) REFERENCES "Account"(account_id) not valid;

alter table "public"."PasswordCredential" validate constraint "PasswordCredential_account_id_fkey";

alter table "public"."PasswordCredential" add constraint "PasswordCredential_account_id_key" UNIQUE using index "PasswordCredential_account_id_key";

alter table "public"."Payment" add constraint "Payment_trip_id_fkey" FOREIGN KEY (trip_id) REFERENCES "Trip"(id) not valid;

alter table "public"."Payment" validate constraint "Payment_trip_id_fkey";

alter table "public"."Rating" add constraint "Rating_trip_id_fkey" FOREIGN KEY (trip_id) REFERENCES "Rider"(id) not valid;

alter table "public"."Rating" validate constraint "Rating_trip_id_fkey";

alter table "public"."Rider" add constraint "Rider_account_id_fkey" FOREIGN KEY (account_id) REFERENCES "Account"(account_id) not valid;

alter table "public"."Rider" validate constraint "Rider_account_id_fkey";

alter table "public"."RiderBankInfo" add constraint "RiderBankInfo_rider_id_fkey" FOREIGN KEY (rider_id) REFERENCES "Rider"(id) not valid;

alter table "public"."RiderBankInfo" validate constraint "RiderBankInfo_rider_id_fkey";

alter table "public"."Token" add constraint "Token_account_id_fkey" FOREIGN KEY (account_id) REFERENCES "Account"(account_id) not valid;

alter table "public"."Token" validate constraint "Token_account_id_fkey";

alter table "public"."Trip" add constraint "Trip_driver_id_fkey" FOREIGN KEY (driver_id) REFERENCES "Driver"(id) not valid;

alter table "public"."Trip" validate constraint "Trip_driver_id_fkey";

alter table "public"."Trip" add constraint "Trip_rider_id_fkey" FOREIGN KEY (rider_id) REFERENCES "Rider"(id) not valid;

alter table "public"."Trip" validate constraint "Trip_rider_id_fkey";

alter table "public"."Vehicles" add constraint "Vehicles_driver_id_fkey" FOREIGN KEY (driver_id) REFERENCES "Driver"(id) not valid;

alter table "public"."Vehicles" validate constraint "Vehicles_driver_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.profiles (id, email, user_type)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'user_type', 'rider')
  );
  RETURN new;
END;
$function$
;


